version: "3"
services:
  nexus:
    image: 192.168.99.100/sonatype/nexus:oss
    ports:
      - "8081:8081"
    volumes:
      - "/Users/anderson/homeoffice/projects/personal/docker/nexus-oss/sonatype-work:/sonatype-work:Z"
    #deploy:
      #restart_policy:
        #condition: on-failure
